# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: IR Crawl

#on:
#  schedule:
#      - cron: '5 * * * *'
#
on:
  push:
    paths:
    - 'docs/event/irbattle/ranking'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Auto list making
      run: |
        cd docs/event/irbattle/ranking
        python -m pip install --upgrade pip
        python3 -m pip install bs4
        python parsedir.py
    - name: Commit files
      run: |
        git config --local user.email "62116388+darksabun@users.noreply.github.com"
        git config --local user.name "GitHub Action"
        git commit -m "IR Score Updated" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.FORACTION }}